Hotfix: try a different approach to running Wafer

diff --git a/.github/workflows/dgd_smoke_test.yml b/.github/workflows/dgd_smoke_test.yml
--- a/.github/workflows/dgd_smoke_test.yml
+++ b/.github/workflows/dgd_smoke_test.yml
@@ -39,8 +39,11 @@ jobs:
       - name: Run wafer
         run: cd wafer && bundle && ruby -Ilib ./exe/wafer >../log/wafer_log.txt 2>&1 &
 
+      - name: Show wafer log
+        run: cat log/wafer_log.txt || echo "Could not find wafer_log.txt"
+
       - name: Test that wafer is running successfully
-        run: pgrep -f "./exe/wafer"
+        run: pgrep -f "rackup -p 2072"
 
       - name: Wait for SkotOS to finish booting.
         run: ./deploy_scripts/shared/wait_for_full_boot.sh
